// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
/// 
/// import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgK5JkMI0Xt7-q2QyAvEG2WPQEnTNzjV4',
    appId: '1:410833609320:web:fe29e1cb37d4d6a7ac91dd',
    messagingSenderId: '410833609320',
    projectId: 'my-farm-f5146',
    authDomain: 'my-farm-f5146.firebaseapp.com',
    storageBucket: 'my-farm-f5146.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBkDvrCmZHlNMqRFpTK65L_ay82ihKyRo',
    appId: '1:410833609320:android:68c3c39a8eb4b708ac91dd',
    messagingSenderId: '410833609320',
    projectId: 'my-farm-f5146',
    storageBucket: 'my-farm-f5146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8HdqBri25l-SKvvk4Q6bBKtAuFInrgSE',
    appId: '1:410833609320:ios:d3b4765d2be09ac1ac91dd',
    messagingSenderId: '410833609320',
    projectId: 'my-farm-f5146',
    storageBucket: 'my-farm-f5146.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8HdqBri25l-SKvvk4Q6bBKtAuFInrgSE',
    appId: '1:410833609320:ios:d3b4765d2be09ac1ac91dd',
    messagingSenderId: '410833609320',
    projectId: 'my-farm-f5146',
    storageBucket: 'my-farm-f5146.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgK5JkMI0Xt7-q2QyAvEG2WPQEnTNzjV4',
    appId: '1:410833609320:web:73f654127cb18a11ac91dd',
    messagingSenderId: '410833609320',
    projectId: 'my-farm-f5146',
    authDomain: 'my-farm-f5146.firebaseapp.com',
    storageBucket: 'my-farm-f5146.firebasestorage.app',
  );
}
